### PR TITLE
Migrate web to PointerButton.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is not tested since the web backend doesn't compile.

### CODE REVIEW

**Review by jneem — APPROVED** [review]
No objections to the change, but maybe we should just remove the web backend if it doesn't compile? xilem was planning for a non-glazier approach on web anyway, right?

**Comment by waywardmonkeys** [comment]
I think that depends on if glazier is meant to be useful beyond xilem or not ...

**Comment by jneem** [comment]
I mean, it isn't useful if it doesn't build...

I guess it's something that can be brought up in office hours, but I'd argue that if no one is maintaining it then we should delete it. It can always be revived from the git history later.

**Comment by raphlinus** [comment]
I'd like to maintain the web backend for embedded demos and documentation, if possible. It was working so hopefully it's not too onerous.

**Pull request merged**
