### PR TITLE
Add missing F-key bindings for xkb and Windows.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
With `keyboard-types` 0.7, we have additional F-keys that can be mapped when using xkb.

On Windows, we had not fully added mappings for some F13-F24.

I haven't found scan codes yet for the F25-F35 keys.

### CODE REVIEW

**Comment by CryZe** [comment]
Is there evidence that these keys even exist?

**Comment by waywardmonkeys** [comment]
Assuming you mean F25-F35, xkb has stuff for them, winit does as well, and the winit folks asked that these get added to `keyboard-types`.

My keyboards are (apparently) rather dull and don't have anything past F12.

**Review by DJMcNab — APPROVED** [review]
Looks good to me! Thanks!

These keys are useful for applications like keyboard remappers, as otherwise useless keys to communicate between applications. For an example, see https://youtu.be/lIFE7h3m40U?t=983 (Tom Scott - The Art of the Bodge: How I Made The Emoji Keyboard at ~16:23)

I personally use the F15 key as a global shortcut for discord's push to talk, to allow the use of a mouse button for this purpose

**Comment by waywardmonkeys** [comment]
In trying some things out, I've found at least a couple of bugs in other code in Glazier ...

**Pull request merged**
