### PR TITLE
Move to Rust 1.71in CI

### PR DESCRIPTION
**Pull request by DJMcNab**
Semi-required #107

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Is this just to be able to use `Option::is_some_and` ?

**Comment by DJMcNab** [comment]
Broadly yes, although the policy (stated just above) is:

> If the version specified here is no longer the latest stable version, then please feel free to submit a PR that adjusts it along with the potential clippy fixes.

That is, we need to update the CI anyway, so that may as happen done it when there's a desire for it. I don't think we document support for anything other than the latest stable.

**Review by xStrom — APPROVED** [review]
I think disabling the clippy check for Wayland until it's replaced is reasonable.

**Comment by xStrom** [comment]
As for how this relates to MSRV - the CI variable isn't meant for MSRV tracking. As in Glazier doesn't currently follow an explicit MSRV. I think that should change (not as part of this PR, but in the future) - however primarily to have clear communication. Until we're shiping actual releases there's not a lot of motivation to keep MSRV lagging behind stable much.

**Pull request merged**
