### PR TITLE
Remove unsafe code in Counter

### LINKED ISSUE #91: Soundness issue with `Counter`
In Glazier there is a counter struct that wraps an atomic number and provides unique IDs. There is a method on it that returns a NonZeroU*, and if the inner number overflows then it will get initialized with zero, which is UB. I don't think the doc comment is sufficient here, unless we mark the methods on the `Counter` as `unsafe`. Alternatively we should acquare exclusive access while we check that the number is not u*::MAX before we increment it and get our ID. This will lead to a little more contention, but the alternative is UB.

### PR DESCRIPTION
**Pull request by jneem**
Fixes #91

### CODE REVIEW

**Review by raphlinus — APPROVED** [review]
Someone 585 years from now will thank us for this change!

**Comment by jneem** [comment]
Only if they increment it once per nanosecond...

**Comment by derekdreery** [comment]
Sorry to be "that guy". :(

**Comment by jneem** [comment]
No worries! Despite the joking, I'm happy to get rid of unneeded unsafe code, and I'm sure the extra branch will be unnoticeable.

**Pull request merged**
